### ISSUE TITLE
missing tex packages needed for texPreview: helvet

### ISSUE THREAD

**Issue by dougwyu** [yonicd/texPreview#46]
package helvetic is present in my installation, so i'm wondering if this is an error in texPreview?

`> texPreview::check_requirements()
  xcolor booktabs multirow    array   helvet  amsmath rotating listings graphicx setspace 
    TRUE     TRUE     TRUE     TRUE    FALSE     TRUE     TRUE     TRUE     TRUE     TRUE 
 caption 
    TRUE 
Warning message:
In texPreview::check_requirements() :
  missing tex packages needed for texPreview: helvet`

**Comment by yonicd** [comment]
see this solution: https://github.com/yonicd/texPreview/issues/30#issuecomment-571737584
