### ISSUE TITLE
File 'standalone.cls' not found.

### ISSUE THREAD

**Issue by dougwyu** [yonicd/texPreview#47]
I'm trying to run texPreview along with equatiomatic

```
library(equatiomatic)
library(texPreview)
# texPreview::check_requirements()
# fit a basic multiple linear regression model
m <- lm(bill_length_mm ~ bill_depth_mm + flipper_length_mm, penguins)
extract_eq(m)
tex_preview(extract_eq(m))
```

and i get this error:

<img width="649" alt="Screenshot 2020-11-22 at 12 03 55" src="https://user-images.githubusercontent.com/12829247/99903208-dbe9bd80-2cba-11eb-8499-8a38704681b1.png">

I'm running 4.0.3 in RStudio 1.4.1043 in macOS 10.15.7 (Catalina)

**Comment by yonicd** [comment]
no problem.

run this in your machine (you'll need `sudo` privliges)

https://github.com/yonicd/texPreview/blob/master/.github/workflows/R-mac.yml#L47

**Comment by dougwyu** [comment]
Thank you, but how do i run a *.yml file?

doug


-- 
Prof. Douglas W. Yu
School of Biological Sciences, University of East Anglia, Norwich, Norfolk  NR4 7TJ  UK,  mob +44-7510-308-272
Kunming Institute of Zoology, 21 Qingsong Lu, Kunming, Yunnan 650201 China 中国云南昆明市盘龙区茨坝青松路21号, ofc +86-871-519 9178, mob +86 183 138 29970
people.uea.ac.uk/en/persons/douglas-yu <https://people.uea.ac.uk/en/persons/douglas-yu>, eastanglia.academia.edu/DouglasYu/Papers <http://eastanglia.academia.edu/DouglasYu/Papers> for pdfs

**Comment by yonicd** [comment]
no. run that line of code in the terminal

```
sudo tlmgr install standalone xcolor booktabs multirow amsmath listings setspace caption graphics tools psnfss varwidth colortbl epstopdf-pkg pgf

```

**Comment by dougwyu** [comment]
ah, thanks

-- 
Prof. Douglas W. Yu
School of Biological Sciences, University of East Anglia, Norwich, Norfolk  NR4 7TJ  UK,  mob +44-7510-308-272
Kunming Institute of Zoology, 21 Qingsong Lu, Kunming, Yunnan 650201 China 中国云南昆明市盘龙区茨坝青松路21号, ofc +86-871-519 9178, mob +86 183 138 29970
people.uea.ac.uk/en/persons/douglas-yu <https://people.uea.ac.uk/en/persons/douglas-yu>, eastanglia.academia.edu/DouglasYu/Papers <http://eastanglia.academia.edu/DouglasYu/Papers> for pdfs
