### ISSUE TITLE
CRAN?

### ISSUE THREAD

**Issue by datalorax** [yonicd/texPreview#57]
Hi! No pressure here at all, but I wanted to check if you'll be submitting to CRAN again soon? If so, I'll wait for that before resubmitting equatiomatic. If not, I'll figure something else out.

**Comment by yonicd** [comment]
Hi

I have been pruning vignettes and tests to get it past the oddities of CRAN. It should be up by end of the week.

**Comment by datalorax** [comment]
Cool, thanks!

**Comment by yonicd** [comment]
passed CRAN submit checks, should be up on their repos by EOD
